root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/zen-basic ."
entrypoint = "./tmp/zen-basic"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["frontend/node_modules", "frontend/dist", "tmp", "bin"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = false

[misc]
clean_on_exit = true